# Generated by Django 3.2.8 on 2021-10-28 11:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=" I'am a proffesional and trustful , Hope i suites u", max_length=200)),
                ('symbol', models.CharField(choices=[('BOOK', 'Book'), ('CHAIR', 'Chair'), ('ROCKET', 'Rocket'), ('TREE', 'Tree')], max_length=15, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=12, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('country', models.CharField(choices=[('EGYPT', 'Egypt'), ('QATAR', 'Qatar'), ('LIBYA', 'Libya')], max_length=20)),
                ('region', models.CharField(choices=[('ELSHARQIYAH', 'el Sharqiyah'), ('CAIRO', 'Cairo'), ('GIZA', 'Giza'), ('ELMENYA ', 'el Menya')], max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('personal_id', models.CharField(max_length=14, unique=True, verbose_name='P.id')),
                ('password', models.CharField(max_length=5, unique=True, verbose_name='vote key')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.region')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voting_on',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 28, 13, 5, 42, 885428))),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.region'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.election'),
        ),
    ]
