# Generated by Django 3.2.8 on 2021-10-28 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting_on',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 28, 13, 58, 35, 703759)),
        ),
    ]
