# Generated by Django 3.2.8 on 2021-10-26 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='votekey',
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(max_length=5, unique=True, verbose_name='vote key'),
        ),
        migrations.AlterField(
            model_name='voting_on',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 26, 22, 57, 33, 25782)),
        ),
    ]
