# Generated by Django 3.2.8 on 2021-10-28 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0002_alter_voting_on_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='votekey',
            field=models.CharField(default='null', max_length=5, unique=True, verbose_name='vote key'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='voting_on',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 28, 17, 5, 26, 229139)),
        ),
    ]
