# Generated by Django 3.2.8 on 2021-10-26 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0002_auto_20211026_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting_on',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 26, 23, 1, 54, 591466)),
        ),
    ]
