# Generated by Django 3.2.8 on 2021-10-26 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0003_alter_voting_on_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting_on',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 26, 23, 2, 16, 879891)),
        ),
    ]
